module.exports.messages = {
    Auth: {
      NO_AUTH: "No auth provided",
      INVALID_CREDENTIALS: "Invalid credentials",
      INVALID_TOKEN: "Invlid or Expire Link",
      USER_EXISTS: "User already exists",
      MERCHANT_EXISTS: "Merchaxnt already exists",
      USER_NOT_FOUND: "User not found",
      MERCHANT_NOT_FOUND: "Merchant not found",
      LOGIN_SUCCESS: "Login success",
      LOGOUT_SUCESS: "Logout success",
      OTP_VERIFY_SUCCESS: "OTP verified successfully",
      OTP_SENT_PHONE: "OTP successfully sent to phone",
      LINK_SENT_EMAIL: "Link successfully sent to email",
      OTP_NOT_VERIFIED: "OTP not verified",
      PASSWORD_RESET_SUCCESS: "Password reset successfully",
      PASSWORD_CHANGE_SUCCESS: "Password changed successfully",
      INVALID_REQ: "Invalid Reqest",
      OTP_NOT_FOUND: "OTP  not found",
      PARAMETER_MISSING: "Parameter missing, please enter the required fields",
      EMAIL_ALREADY_ASSOCIATED: "Email already associated with another account",
      PHONE_ALREADY_ASSOCIATED: "Phone already associated with another account",
      OTP_SENT_PHONE: "OTP successfully sent to phone",
      OTP_NOT_FOUND: "OTP not found",
      USER_VERIFY_PENDING: "User account verification is pending",
      DATA_NOT_FOUND: "Data not found",
      ADDED_SUCCESSFULLY: "Data added to database successfully",
      PASSWORD_NOT_MATCH: "Incorrect!! Old Password",
      EMAIL_SENT_SUCCESSFULLY: "Email sent successfully",
      INVALID_TOKEN: "Invalid token",
      EMAIL_VERIFIED: "Email verified successfully",
      VERIFY_SENT_EMAIL: "Verification sent to email",
      USERNAME_TAKEN: "Username already taken, try another one",
      PRODUCT_EXITS: "Product already exist",
      PRODUCT_NOT_FOUND: "Product not found",
      SUCCESS: "SUCCESS",
      NOT_FOUND: "Data not found",
      FILE_NOT_UPLOADED: "Kinldy, upload a file.",
    },
    Customer: {
      SUCCESS: "Success",
      CREATED: "User created successfully",
      PROFILE_UPDATE_SUCCESS: "User updated successfully",
      PENDING_STATUS_ERROR: "Profile verification is pending",
      GET_PROFILE: "Profile Fetch Successfully",
      EDIT_PROFILE: "Profile Edit Successfully",
      OUT_OF_SERVICE_AREA: "Customer is out of service area",
      CATEGORY_TYPES: "Category Types Fetch Successfully",
      TRENDING_ITEMS: "Trending Items Fetch Successfully",
      SPECIAL_ITEMS: "Special Items Fetch Successfully",
      HEALTHY_ITEMS: "Healthy Items Fetch Successfully",
      ON_SALE_ITEMS: "Items On Sale Fetch Successfully",
      NO_ITEMS: "Items Not Found",
      BENNERS: "Banners Fetch Successfully",
      FEATURED_PRODUCTS: "Featured Products Fetch Successfully",
      FAVORITES: "Favorites Fetch Successfully",
      DEALS: "Deals Fetch Successfully",
      BRANDS: "Big Brands Fetch Successfully",
      CREATE_ORDER: "Order Generated Successfully",
      VERIFIED_SUCCESS: "Customer Verified Successfully",
      VERIFIED_FAILED: "Not a Verified Customer",
      SEARCH_RESULTS: "Search Results Fetch Successfully",
      FILTERED_ITEMS: "Filtered Items Fetch Successfully",
      ORDER_ITEMS_EMPTY: "Order Should Contain Atleast One Item",
      GET_ORDERS: "Orders Fetch Successfully",
      PARAMETER_MISSING: "Parameter Missing",
      SHIPPING: "Shipping Generated Successfully",
      ADD_ADDRESS: "Added new Address Successfully",
      EditAddress: "Edit Address Successfully",
      Delete: "Deleted from DB",
      DOES_NOT_EXIST: "Does Not exist in DB"
    },
    Driver: {
      CREATED: "User created successfully",
      PROFILE_UPDATE_SUCCESS: "User updated successfully",
      PENDING_STATUS_ERROR: "Profile verification is pending",
      PROFILE_FETCH_SUCCESS: "Profile fetched successfully",
      STATUS_UPDATE_SUCCESS: "Status updated successfully",
      DRIVER_ONLINE: "Status changed to online",
      DRIVER_OFFLINE: "Status changed to offline",
      ORDER_FETCH_SUCCESS: "Orders fetched successfully",
      PROOF_REQUIRED: "Proof is required",
      UPLOAD_SUCCESS: "Uploaded successfully",
      ORDER_UPDATE_SUCCESS: "Order updated successfully",
    },
    Merchant: {
      MERCHANT_NOT_FOUND: "Merchant not found !",
      CREATED: "User created successfully",
      PROFILE_UPDATE_SUCCESS: "User updated successfully",
      PENDING_STATUS_ERROR: "Profile verification is pending",
      USERNAME_TAKEN: "Username already taken, try another one",
      ITEM_TYPES: "All Items Types",
      BENNERS: "Featured Banners",
      INTERNAL_SERVER_ERROR: "Some error occoured , Please contact the support team ",
      MERCHANT_NOT_VERIFIED: "Merchant is not verified",
      PRODUCT_CREATED: "Product added successfully",
      PRODUCT_EDITED: "Product updated succesfully",
    },
    Admin: {
      ITEM_CREATED: "Item Successfully Created",
      BANNER_CREATED: "Banner Successfully Created",
      BRAND_CREATED: "Brand Successfully Created",
      BRAND_EXIST: "Brand Already Exist",
      PROFILE_UPDATE_SUCCESS: "Admin updated successfully",
    },
    File: {
      NOT_FOUND: "Picture not found",
    },
    Store: {
      ALL_STORES: "All Stores Fetch Successfully",
      NOT_FOUND: "Store not found",
      REMOVE_FAV_SUCCESS: "Favorite Store Removed Successfully",
      ADD_FAV_SUCCESS: "Favorite Store Added Successfully",
      FAVORITES_STORE: "Favorite Stores Fetch Successfully",
      ADD_VISITED_SUCCESS: "Visited Store Updated Successfully",
      ALLREADY_VISITED: "Store Already Visited",
      VISITED_STORE: "Visited Stores Fetch Successfully",
      RECOMMENDED_STORE: "Recommended Stores Fetch Successfully",
    },
  };
  